cat/urls.py
from . import views
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import CatList, CatDetail, CatCreateView, EditCat, DeleteCat


urlpatterns = [
    path(
        'cat/',
        CatList.as_view(),
        name='cat'
    ),
    path(
        'cat/<int:pk>',
        CatDetail.as_view(),
        name='cat_detail'
    ),
    path(
        'cat/add/',
        login_required(CatCreateView.as_view()),
        name='add_cat'
    ),
    path(
        'cat/edit/<int:pk>/',
        login_required(EditCat.as_view()),
        name='edit_cat'
    ),
    path(
        'cat/delete/<int:pk>/',
        login_required(DeleteCat.as_view()),
        name='delete_cat'
    ),
]

purrfect_sitters/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls')),
    path('', include('service.urls')),
    path('', include('cat.urls')),
    path('', include('booking.urls')),
    path('', include('checkout.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from . import views
from django.urls import path
from .views import ServiceList


urlpatterns = [
    path('service/', ServiceList.as_view(), name='services'),
]

service/models.py
from django.db import models


class Services(models.Model):
    """
    Model for the information about the services on offer.
    Includes service name, description, price and package choice.
    """

    service_name = models.CharField(
        max_length=100,
        verbose_name="Service Name"
    )

    service_description = models.TextField(
        max_length=400,
        verbose_name="Service Description"
    )

    price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        verbose_name="Package Price"
    )

    SERVICE_CHOICES = [
        ("1", "30 minutes"),
        ("2", "60 minutes"),
    ]

    service_choice = models.CharField(
        max_length=50,
        choices=SERVICE_CHOICES,
        null=True,
        verbose_name="Service Choice"
    )

    class Meta:
        verbose_name_plural = "Services"

    def __str__(self):
        return f"{self.service_name}"

service/views.py
from django.shortcuts import render
from django.views import generic
from .models import Services


class ServiceList(generic.ListView):
    """
    View that displays the service name, description and price
    """
    model = Services

    queryset = Services.objects.all()
    template_name = 'service/services.html'

service/templates/service/services.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %} - Services{% endblock %}

{% block extra_meta %}
{% endblock %}

{% block content %}

<!-- Package Description Section -->
    <div class="row p-4">
        <div class="col-12">
            <h1>Our Services</h1>
            <p>Find out more about our packages and our frequently asked questions.</p>
            <a href="{% url 'booking' %}" class="btn btn-custom-dark mt-2 btn-lg">Book now</a>
        </div>
    </div>

    <div class="row p-4">
        <div class="col-sm-12 col-xl-6">
            {% for service in services_list %}
                <article class="d-flex pt-3">
                    <div class="p-2 bd-highlight">
                        <h2><i class="fa-solid fa-paw"></i> {{ service.service_name }}</h2>
                        <p class="font-weight-bold">{{ service.get_service_choice_display }}</p>
                        <div>{{ service.service_description | safe }}</div>
                        <p>£{{ service.price }}</p>
                    </div>
                </article>
            {% endfor %}
        </div>
    </div>  
    <hr class="line-break">

    <!-- Frequently Asked Questions -->
    <h2 class="pt-2">Frequently Asked Questions</h2>
    <div class="accordion pt-2" id="accordionExample">
        <div class="card">
            <div class="card-header" id="headingOne">
                <h3 class="mb-0">
                    <button class="btn btn-link text-body accordion-button" type="button" data-toggle="collapse" data-target="#collapseOne"
                        aria-expanded="true" aria-controls="collapseOne">
                        How far in advance should I book a sitter?
                    </button>
                </h3>
            </div>

            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                <div class="card-body">
                    The earlier, the better. But of course, we understand that life happens and sometimes you need something at the last minute.
                    Book the date you need and we'll do our best to make a plan!
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" id="headingTwo">
                <h3 class="mb-0">
                    <button class="btn btn-link collapsed text-body accordion-button" type="button" data-toggle="collapse" data-target="#collapseTwo"
                        aria-expanded="false" aria-controls="collapseTwo">
                        What if I have special requests for my cats?
                    </button>
                </h3>
            </div>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                <div class="card-body">
                    We love all the quirks and oddities of our feline friends which is why we love what we do!
                    Please ensure to describe your bestie in as best as possible on their profile.
                    You can also make special requests when booking, we'll do our best to make it happen.
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" id="headingThree">
                <h3 class="mb-0">
                    <button class="btn btn-link collapsed text-body accordion-button" type="button" data-toggle="collapse" data-target="#collapseThree"
                        aria-expanded="false" aria-controls="collapseThree">
                        My cat has a medical condition, are you willing to administer medication?
                    </button>
                </h3>
            </div>
            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                <div class="card-body">
                    It can be very stressful leaving your furries when they're not 100% and we understand your concern.
                    For cats with ongoing conditions, we're happy to ensure their medication is administered as required.
                    Make sure to add this special request (and any tips for successful ingestion, we know tablets can be tricky!) when making a booking.
                    For cats that have more acute care needs, we'll need to review on a case by case basis whether we can assist.
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" id="headingFour">
                <h3 class="mb-0">
                    <button class="btn btn-link collapsed text-body accordion-button" type="button" data-toggle="collapse" data-target="#collapseFour"
                        aria-expanded="false" aria-controls="collapseFour">
                        What happens in an emergency?
                    </button>
                </h3>
            </div>
            <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
                <div class="card-body">
                    These things happen and our sitters are well equipped to handle it.
                    Please ensure the correct and up-to-date vet contact details are on your profile.
                    Prior to your time away, your assigned cat sitter will be in touch to discuss protocols with you so we're on the same page.
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" id="headingFive">
                <h3 class="mb-0">
                    <button class="btn btn-link collapsed text-body accordion-button" type="button" data-toggle="collapse" data-target="#collapseFive"
                        aria-expanded="false" aria-controls="collapseFive">
                        I have more than 3 cats, what is your rate?
                    </button>
                </h3>
            </div>
            <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordionExample">
                <div class="card-body">
                    There is a surcharge added for each additional cat above 3 which accounts for the additional time
                    and effort by our sitters to make sure each and every member of your feline household are taken care of.
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" id="headingSix">
                <h3 class="mb-0">
                    <button class="btn btn-link collapsed text-body accordion-button" type="button" data-toggle="collapse" data-target="#collapseSix"
                        aria-expanded="false" aria-controls="collapseSix">
                        I want the sitter to spend more than 60 minutes with my cat is that possible?
                    </button>
                </h3>
            </div>
            <div id="collapseSix" class="collapse" aria-labelledby="headingSix" data-parent="#accordionExample">
                <div class="card-body">
                    This will have to be handeled on a case by case basis. 
                    Ensure to add this request to your booking and we'll be in touch.
                    Please note, our sitters are not live-in.
                </div>
            </div>
        </div>
    </div>

{% endblock %}